version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/db
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=travel
      - MYSQL_USER=sergei
      - MYSQL_PASSWORD=password
  postgresql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/db
    environment:
      - POSTGRES_DB=travel
      - POSTGRES_USER=sergei
      - POSTGRES_PASSWORD=password